Class {
	#name : #CMIDAIRRPGCitizenResourceDynamics,
	#superclass : #CMIDAIRCitizenResourceDynamics,
	#category : #'Cormas-Model-IDAIR-Resource-RPG'
}

{ #category : #operations }
CMIDAIRRPGCitizenResourceDynamics >> citizenHospitalized [

	
]

{ #category : #operations }
CMIDAIRRPGCitizenResourceDynamics >> citizenICUed [


]

{ #category : #operations }
CMIDAIRRPGCitizenResourceDynamics >> citizenQuarrantined [


]

{ #category : #operations }
CMIDAIRRPGCitizenResourceDynamics >> citizenReleased [

	
]

{ #category : #testing }
CMIDAIRRPGCitizenResourceDynamics >> hasIsolation [

	^ false
]

{ #category : #accessing }
CMIDAIRRPGCitizenResourceDynamics >> personalPreventionFactor [

	^ 0.0
]

{ #category : #controlling }
CMIDAIRRPGCitizenResourceDynamics >> step [
	
]
